### ISSUE TITLE
NVM Is Expected In `varie` CLI Command

### ISSUE THREAD

**Issue by mikebronner** [variejs/varie#10]
When running `varie new xxxx` I get the following error if NVM is not installed:
```sh
varie new xxxx
✔ Created xxxx
✖ Error: Command failed: cd /Users/mike/Developer/Sites/xxxx && export NVM_DIR="$HOME/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" && nvm use && npm install
```

**Comment by lukepolo** [comment]
We pushed up a fix in varie-cli , make sure your using 0.0.24

**Comment by mikebronner** [comment]
<img width="391" alt="screen shot 2018-07-05 at 9 51 58 am" src="https://user-images.githubusercontent.com/1791050/42336631-16544142-8039-11e8-843f-03b14fda6cfd.png">

Thanks!

If I may make a feature suggestion: would be nice for the command to CD me into the project so I'm ready to go. :)

**Comment by lukepolo** [comment]
Im not sure thats possible unless i changed the implementation will look at it sometime
