### ISSUE TITLE
Running `npm run watch` opens the site using the external URL, which doesn't resolve.

### ISSUE THREAD

**Issue by mikebronner** [variejs/varie#12]
When running `npmn run watch`, the browser tries to open to `http://varie.test:3000`, but that is not resolvable:

![screen shot 2018-07-03 at 7 17 08 pm](https://user-images.githubusercontent.com/1791050/42253248-b9dd68ba-7ef5-11e8-8322-2f740b68fde1.png)

However, accessing the site under `http://localhost:3000` works perfectly. Changing the configuration in `webpack.config.js` to say localhost worked:
```js
  const config = {
    appName: "Varie",
    host: "localhost",
```

I suppose the presumption here is that the developer has the domain entry in their hosts file. Maybe adding a paragraph to the docs would help those unfamiliar with the project (idiots like me). hehe

**Comment by lukepolo** [comment]
We added back in the .env so you can change the defaults for webpack easily
