### ISSUE TITLE
Error: Incorrect Peer Dependency

### ISSUE THREAD

**Issue by mikebronner** [variejs/varie#16]
I'm getting the following error when running `yarn` on a fresh Varie project (v0.3.3):
```
warning "varie-bundler > img-loader@3.0.0" has incorrect peer dependency "imagemin@^5.0.0"
```

**Comment by lukepolo** [comment]
Pretty odd not sure why : 

![image](https://user-images.githubusercontent.com/2066668/44791360-70fabc00-ab6f-11e8-84fa-0a613d669c5d.png)

Will have to look more into it

**Comment by lukepolo** [comment]
Its a false positive, I did a fresh install and saw that the image min is actually installed
