### ISSUE TITLE
Nested Components Issue

### ISSUE THREAD

**Issue by rebz** [variejs/varie#4]
I've noticed that when using a component within a component that sometimes Varie will freak out.

Example being:

````
Core.vue Layout
    - imports CoreHeader.vue
        - imports CoreNavigation.vue
            - router-link
````

The above is how I do things outside of Varie and it works just as expected. However Varie claims that `<router-link>` is not a registered component.

If I do the following instead, it works...

````
Core.vue Layout
    - router-link (moved up 2 layers)
    - imports CoreHeader.vue
        - imports CoreNavigation.vue
````

It seems that when I nest `<router-link>` one additional component layer it is not resolving correctly.

Even placing `<router-link>` inside of `CoreHeader.vue` produces the same error.

**Comment by rebz** [comment]
Looks like fixing https://github.com/variejs/varie/issues/3 MIGHT solve this issue. It does for me initially, but not sure if there are further reaching examples that do not fit inside this fix.

**Comment by lukepolo** [comment]
@rebz did this fix it?

**Comment by rebz** [comment]
It appears to be fixed. I say we close for now and if I happen to find a separate issue I'll open it up.
