### ISSUE TITLE
Catch All Route - Catches too much

### ISSUE THREAD

**Issue by rebz** [variejs/varie#5]
`$router.route("*", "404");`

Whether I put this towards the top or the bottom of my `routes/index.ts` it is catching too many routes, even routes that are previously specified; before or after does not change.

I can give more info if asked. Just wanted to quickly capture this issue before I forget.

**Comment by lukepolo** [comment]
@rebz after fixing the routes, did this fix the issue?

**Comment by rebz** [comment]
It seems to have fixed a majority of the issues, yes. There is only one item left, but it may be by design.

When `$router.route("*", "404");` lives outside any `.prefix()` or `.template()` it works just as expected.

When I put it inside a `.template()` for example, it appears to catch only routes that are not specified; excellent. However, when it does catch a route, it completely ignores any parent layouts defined in a `.prefix()` or `.template()`. See example route below:

![image](https://user-images.githubusercontent.com/628385/36074544-327e84e0-0f0f-11e8-8856-6b97a540f869.png)

I expect the 404 error to show INSIDE of the `layout/core.vue` file. Below is what I get...

![image](https://user-images.githubusercontent.com/628385/36074553-5dbcea84-0f0f-11e8-9cb5-3eddc853a8a6.png)

Below is what successful routes normally look like.

![image](https://user-images.githubusercontent.com/628385/36074556-70e8b174-0f0f-11e8-8b06-010eb7b8376c.png)

**Comment by rebz** [comment]
### Additional information...

If I move the 404 to the top of its parent `.template()` it will inherit the core layout.

![image](https://user-images.githubusercontent.com/628385/36074562-b1f08444-0f0f-11e8-96af-4f6d3b9754f3.png)

![image](https://user-images.githubusercontent.com/628385/36074564-b76e9000-0f0f-11e8-8e5f-8cbfcfad741e.png)

**Comment by rebz** [comment]
I should note that adding `/*` to the 404 route will cause it to catch everything when inside `.template()`.

**Comment by lukepolo** [comment]
This was a toughie! Fixed 0.0.31
