### ISSUE TITLE
Issue w/ expectations around Routes, Router Views, Parent Layouts, and Prefixes

### ISSUE THREAD

**Issue by rebz** [variejs/varie#6]
Current `routes/index.ts`
![image](https://user-images.githubusercontent.com/628385/36063764-2f4ffef4-0e4f-11e8-9c29-122d613ebf39.png)

Expectation for going to `/people`
![corelayout](https://user-images.githubusercontent.com/628385/36063847-204180e4-0e50-11e8-882e-3780a0a399fa.png)

Would like to see Core absorbed as the primary layout which has a `<router-view>` loading `resources/views/people/layout.vue` with its own `<router-view>` that loads `resources/views/people/index.vue`.

The current functionality is a bit wonky and depending on how I reference the `path` within `.template()` or `.route()` I am unable to achieve the desired effect.

**Comment by rebz** [comment]
More information...

### Visiting `/`
![image](https://user-images.githubusercontent.com/628385/36064042-28f17e4e-0e53-11e8-949a-fcd032af5ac3.png)

---

### Visiting `/people`
![image](https://user-images.githubusercontent.com/628385/36064046-3bccc3f2-0e53-11e8-92a6-ef03cfd186ef.png)

---

### Clicking on `People`
![image](https://user-images.githubusercontent.com/628385/36064058-5ff4c43c-0e53-11e8-9b97-5377c84a8767.png)

This is via `<router-link :to="{ name: 'people' }">People</router-link>` which is part of the core layout... notice the URL.

**Comment by rebz** [comment]
You can play with my structure at https://github.com/rebz/vuejs-varie

**Comment by rebz** [comment]
Reference for attempted structure.

![router-component-structure](https://user-images.githubusercontent.com/628385/36064163-c616360a-0e54-11e8-864d-6f3ddf10d01b.png)

**Comment by rebz** [comment]
Tweaked the route file to...

![image](https://user-images.githubusercontent.com/628385/36064234-d08a12e0-0e55-11e8-86da-5e000eefc887.png)

---

Playing with the routes by navigating via `<router-link>`, going to the manual route, removing the forward slash from the URL, refreshing, etc. You'll notice that sometimes the styles do not load the `body` element receives 8px margin (default for Chrome); not using my reset styles.

![varie-routes](https://user-images.githubusercontent.com/628385/36064242-297eb9a0-0e56-11e8-9307-dd1717daa9a4.gif)

**Comment by lukepolo** [comment]
This has been fixed, thanks for the report!
