### ISSUE TITLE
CSS Issue w/ routes/index.ts

### ISSUE THREAD

**Issue by rebz** [variejs/varie#7]
Generated routes are noted as acting weird in a previous issue. This was an additional example of it interfering with linked stylesheets. You'll notice the CSS file loading from `/people/css` when it should be coming directly from `/css`.

## Current URL
![image](https://user-images.githubusercontent.com/628385/36065250-26ccf9f0-0e66-11e8-9684-559b57d5ed4a.png)

## CSS URL
![image](https://user-images.githubusercontent.com/628385/36065281-5e27952c-0e66-11e8-802f-5768953b65c5.png)

## Route Structure
![image](https://user-images.githubusercontent.com/628385/36065242-083c0846-0e66-11e8-83e5-86a25d836b25.png)

**Comment by lukepolo** [comment]
For now we will add a base `<base href="/">` but will need to make a PR to laravel mix
