### ISSUE TITLE
Router - Nested Routes w/ Params and Parent Layouts

### ISSUE THREAD

**Issue by rebz** [variejs/varie#8]
## Repository of Issue
Use the `issue-route-params` branch.
https://github.com/rebz/vuejs-varie/tree/issue-route-params

## Routes File

![image](https://user-images.githubusercontent.com/628385/36075709-aa80026e-0f20-11e8-9e57-8c499dfeded0.png)

## People Index View

![image](https://user-images.githubusercontent.com/628385/36075730-0317b2be-0f21-11e8-922d-7986477dbd96.png)

## Gif of Output

![varie-route-params](https://user-images.githubusercontent.com/628385/36075771-6a3a92a4-0f21-11e8-9fdb-21b6d9d642b4.gif)

You'll notice in the GIF that it looks like it is outputting the correct view `people/view.vue`, however the URL is now root with the param appended; e.g., `http://varie.test/1`. The URL should be `http://varie.test:/people/1`.

**Comment by lukepolo** [comment]
This was a toughie! Fixed 0.0.31
